### ISSUE TITLE
document packages needed for development

### ISSUE THREAD

**Issue by glensc** [linux-pam/linux-pam#30]
in process of #28 had to guess which packages setup build dependencies.

however things are still broken, like:
https://travis-ci.org/glensc/linux-pam/jobs/254525436

```
make[2]: Entering directory `/home/travis/build/glensc/linux-pam/modules/pam_access'
make[2]: *** No rule to make target `access.conf.5', needed by `all-am'.  Stop.
make[2]: Leaving directory `/home/travis/build/glensc/linux-pam/modules/pam_access'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/glensc/linux-pam/modules'
make: *** [check-recursive] Error 1
```

this got broken just with dist change: `precise` -> `trusty`

it's nowhere documented (at least i couldn't find) what packages are required and what are optional dependencies or are there alternatives

**Comment by cktenn** [comment]
I read configure.ac, and after install elinks, I built pam successfully.

**Comment by baudelee** [comment]
> configure.ac,

Hi ， i also encounter this problem, as i can't find configure.ac file in linux-pam-Linux-PAM-1_1_0 version source, only find configure.in, Could you tell me which package installed to solve this problem?

Thanks !

**Comment by t8m** [comment]
1.1.0 is extremely old. The configure.in was renamed to configure.ac later.

**Comment by baudelee** [comment]
Thanks a lot! Could you know how to resolve this compile problem? i don't know which one dependence to install.

**Comment by baudelee** [comment]
Our product used this old version, i should to compile it by myself.

**Comment by Keno** [comment]
I also ran into this and can confirm that installing `elinks` or `w3m` solves the issue. Of course it would be nice if either configure failed with an informative error or the build process was fixed such that not building the documentation is not fatal.

**Comment by Necktwi** [comment]
I use `Gentoo`. Installing `w3m` didn't fix the issue and I don't understand why would it fix the issue. @cktenn, `AC_ARG_ENABLE([regenerate-docu]` don't hint me any dependencies
```
AC_ARG_ENABLE([regenerate-docu],
  AS_HELP_STRING([--disable-regenerate-docu],[Don't re-build documentation
  from XML sources]),
  [enable_docu=$enableval], [enable_docu=yes])

```

**Comment by Necktwi** [comment]
installing `libxml2` or `texinfo` fixed the issue.

**Comment by Jnchi** [comment]
@Necktwi, just checkout the [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-libs/pam/pam-1.3.1-r1.ebuild).

**Comment by publicsite** [comment]
I fixed this error on debian (No rule to make target `access.conf.5') by installing fop.

sudo apt-get install fop

Cheers,

Josh

**Comment by sateesh12** [comment]
I still continue to find this build error. I am trying to build on raspian-buster. Installed already sudo apt-get install shtools libtool autoconf autopoint.c.
My configure command is as follows:
pi@raspberrypi3:~/linux-pam $ ./configure --disable-regenrate-docu LDFLAGS=-static

Please help.

**Comment by sateesh12** [comment]
[SOLVED] Downloading + untar + ./configure --disable-regenerate-docu --enable-static=yes --disable-pie --disable-prelude --disable-cracklib --disable-audit --enable-db=no --disable-nis --disable-selinux --disable-econf --disable-nls --disable-rpath
+ make the PAM from the following location [SOLVED] the build issue.
https://github.com/linux-pam/linux-pam/releases/download/v1.3.1/Linux-PAM-1.3.1.tar.xz

**Comment by Necktwi** [comment]
@Jnchi that's why portage is cool.

**Comment by funkcjonusz** [comment]
Still not fixed.
Solution you can find here: [link](https://github.com/linux-pam/linux-pam/pull/28/commits/177e44dd74e5ec5d4c5229cf84686c0d18059ada)
In one line: sudo apt-get -qq install automake autopoint gettext xsltproc docbook-xml docbook-xsl libxml2-utils

**Comment by youling257** [comment]
Ubuntu Focal Fossa
apt-get -qq install automake autopoint gettext xsltproc docbook-xml docbook-xsl libxml2-utils

no help! still No rule to make target `access.conf.5' !

**Comment by alexal** [comment]
@youling257 ,

You can bypass it by using the following option:

`./configure **--disable-doc**`

**Comment by alexal** [comment]
On Ubuntu, you have to install these packages to compile Linux PAM:
- autoconf
- automake
- autopoint
- bison
- bzip2
- docbook-xml
- docbook-xsl
- flex
- gettext
- libaudit-dev
- libcrack2-dev
- libdb-dev
- libfl-dev
- libselinux1-dev
- libtool
- libxcrypt-dev
- libxml2-utils
- make
- pkg-config
- sed
- w3m
- xsltproc
- xz-utils
- gcc

**Comment by ldv-alt** [comment]
Does ci/install-dependencies.sh help?

**Comment by ldv-alt** [comment]
Resolved by c3255ed4d4110c4a346d87be0bd5572fe9b0bae5.

**Comment by AndrewGMorgan** [comment]
After much diffing and reading of logs, I found that 'elinks' was needed to build the sources under Fedora.

**Comment by t8m** [comment]
> After much diffing and reading of logs, I found that 'elinks' was needed to build the sources under Fedora.

In the current version you need either w3m or elinks.

**Comment by 5andr0** [comment]
I had to install **docbook-xsl** for the **xsltproc** command to parse [http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl](http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl)

**Comment by opensignature** [comment]
unfortunately in lubuntu bionic beaver none of the suggestions proposed worked, so  ./configure --disable-doc
